#include "markforge/plugin.h"
#include "markforge/fs.h"
void mf_plugin_metadata_init(mf_plugin_metadata_t*m,const char*name,const char*version,const char*desc){ if(m){ memset(m,0,sizeof(*m)); snprintf(m->name,sizeof(m->name),"%s",name?name:"plugin"); snprintf(m->version,sizeof(m->version),"%s",version?version:"1.0"); snprintf(m->api_version,sizeof(m->api_version),"%s",MF_VERSION_STRING); snprintf(m->description,sizeof(m->description),"%s",desc?desc:""); } }
int mf_plugin_is_compatible(const mf_plugin_metadata_t*m){ return m && m->api_version[0] && m->api_version[0]==MF_VERSION_STRING[0]; }
void mf_plugin_manager_init(mf_plugin_manager_t*m,mf_renderer_manager_t*r,mf_hook_manager_t*h){ if(m){ mf_vector_init(&m->plugins); m->context.renderers=r; m->context.hooks=h; m->context.sandbox_mode=1; } }
void mf_plugin_manager_destroy(mf_plugin_manager_t*m){ size_t i; if(!m)return; mf_plugin_unload_all(m); for(i=0;i<m->plugins.size;i++) free(m->plugins.items[i]); mf_vector_destroy(&m->plugins); }
mf_result_t mf_plugin_register(mf_plugin_manager_t*m,const mf_plugin_t*p){ mf_plugin_t*c; if(!m||!p||!mf_plugin_is_compatible(&p->metadata))return MF_ERROR_INVALID; c=(mf_plugin_t*)malloc(sizeof(*c)); if(!c)return MF_ERROR_NOMEM; *c=*p; c->loaded=0; return mf_vector_push(&m->plugins,c); }
mf_result_t mf_plugin_load_all(mf_plugin_manager_t*m){ size_t i; if(!m)return MF_ERROR_INVALID; for(i=0;i<m->plugins.size;i++){ mf_plugin_t*p=(mf_plugin_t*)m->plugins.items[i]; if(!p->loaded){ if(p->init && p->init(&m->context)!=MF_OK)return MF_ERROR; p->loaded=1; if(m->context.hooks) mf_hook_emit(m->context.hooks,MF_HOOK_PLUGIN_LOADED,p); } } return MF_OK; }
void mf_plugin_unload_all(mf_plugin_manager_t*m){ size_t i; if(!m)return; for(i=0;i<m->plugins.size;i++){ mf_plugin_t*p=(mf_plugin_t*)m->plugins.items[i]; if(p->loaded){ if(p->shutdown)p->shutdown(&m->context); p->loaded=0; if(m->context.hooks) mf_hook_emit(m->context.hooks,MF_HOOK_PLUGIN_UNLOADED,p); } } }
void mf_plugin_manager_list(const mf_plugin_manager_t*m,FILE*out){ size_t i; if(!out)out=stdout; if(!m)return; for(i=0;i<m->plugins.size;i++){ mf_plugin_t*p=(mf_plugin_t*)m->plugins.items[i]; fprintf(out,"%s %s %s\n",p->metadata.name,p->metadata.version,p->loaded?"loaded":"registered"); } }
mf_result_t mf_plugin_discover_manifest(mf_plugin_manager_t*m,const char*path){ mf_plugin_t p; char name[64]; const char*base; if(!m||!path)return MF_ERROR_INVALID; base=mf_path_basename(path); snprintf(name,sizeof(name),"%s",base); mf_plugin_metadata_init(&p.metadata,name,"1.0","manifest plugin"); p.init=NULL; p.shutdown=NULL; p.loaded=0; return mf_plugin_register(m,&p); }
